// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: config.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NOTIFICATION_METHOD int32

const (
	NOTIFICATION_METHOD_UNSPECIFIED NOTIFICATION_METHOD = 0
	NOTIFICATION_METHOD_GOTIFY      NOTIFICATION_METHOD = 1 // Gotify notification service
	NOTIFICATION_METHOD_NTFY        NOTIFICATION_METHOD = 2 // Ntfy notification service
	NOTIFICATION_METHOD_EMAIL       NOTIFICATION_METHOD = 3 // uses [Gmail only] SMTP
	NOTIFICATION_METHOD_SMS         NOTIFICATION_METHOD = 4 // uses SMS
	NOTIFICATION_METHOD_LOG         NOTIFICATION_METHOD = 5 // [FOR DEBUGGING] Log to console
)

// Enum value maps for NOTIFICATION_METHOD.
var (
	NOTIFICATION_METHOD_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "GOTIFY",
		2: "NTFY",
		3: "EMAIL",
		4: "SMS",
		5: "LOG",
	}
	NOTIFICATION_METHOD_value = map[string]int32{
		"UNSPECIFIED": 0,
		"GOTIFY":      1,
		"NTFY":        2,
		"EMAIL":       3,
		"SMS":         4,
		"LOG":         5,
	}
)

func (x NOTIFICATION_METHOD) Enum() *NOTIFICATION_METHOD {
	p := new(NOTIFICATION_METHOD)
	*p = x
	return p
}

func (x NOTIFICATION_METHOD) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NOTIFICATION_METHOD) Descriptor() protoreflect.EnumDescriptor {
	return file_config_proto_enumTypes[0].Descriptor()
}

func (NOTIFICATION_METHOD) Type() protoreflect.EnumType {
	return &file_config_proto_enumTypes[0]
}

func (x NOTIFICATION_METHOD) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NOTIFICATION_METHOD.Descriptor instead.
func (NOTIFICATION_METHOD) EnumDescriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{0}
}

type Config struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PassivePipeline []*PassivePipeline     `protobuf:"bytes,1,rep,name=passive_pipeline,json=passivePipeline,proto3" json:"passive_pipeline,omitempty"`
	TaskSystems     []*TaskSystem          `protobuf:"bytes,2,rep,name=task_systems,json=taskSystems,proto3" json:"task_systems,omitempty"`
	Piles           []*PileConfig          `protobuf:"bytes,3,rep,name=piles,proto3" json:"piles,omitempty"`
	Users           []*User                `protobuf:"bytes,4,rep,name=users,proto3" json:"users,omitempty"`
	Notifications   *NotificationConfig    `protobuf:"bytes,5,opt,name=notifications,proto3" json:"notifications,omitempty"`
	Meals           *MealConfig            `protobuf:"bytes,6,opt,name=meals,proto3" json:"meals,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetPassivePipeline() []*PassivePipeline {
	if x != nil {
		return x.PassivePipeline
	}
	return nil
}

func (x *Config) GetTaskSystems() []*TaskSystem {
	if x != nil {
		return x.TaskSystems
	}
	return nil
}

func (x *Config) GetPiles() []*PileConfig {
	if x != nil {
		return x.Piles
	}
	return nil
}

func (x *Config) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *Config) GetNotifications() *NotificationConfig {
	if x != nil {
		return x.Notifications
	}
	return nil
}

func (x *Config) GetMeals() *MealConfig {
	if x != nil {
		return x.Meals
	}
	return nil
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName     string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Phone         *string                `protobuf:"bytes,5,opt,name=phone,proto3,oneof" json:"phone,omitempty"` // optional, for notifications
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{1}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *User) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetPhone() string {
	if x != nil && x.Phone != nil {
		return *x.Phone
	}
	return ""
}

type PileConfig struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Subpiles         []*PileConfig          `protobuf:"bytes,2,rep,name=subpiles,proto3" json:"subpiles,omitempty"`
	Name             string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description      string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	UnitSingular     string                 `protobuf:"bytes,5,opt,name=unit_singular,json=unitSingular,proto3" json:"unit_singular,omitempty"`
	UnitPlural       string                 `protobuf:"bytes,6,opt,name=unit_plural,json=unitPlural,proto3" json:"unit_plural,omitempty"`
	UnitAbbreviation string                 `protobuf:"bytes,7,opt,name=unit_abbreviation,json=unitAbbreviation,proto3" json:"unit_abbreviation,omitempty"`
	UnitAtomicScale  int32                  `protobuf:"varint,8,opt,name=unit_atomic_scale,json=unitAtomicScale,proto3" json:"unit_atomic_scale,omitempty"` // the total value of the pile divided by this value gives the number of units; e.g. with this = 4, adding 1 to the pile is adding 1/4 gallon
	InitialValue     int32                  `protobuf:"varint,9,opt,name=initial_value,json=initialValue,proto3" json:"initial_value,omitempty"`
	MaxValue         int32                  `protobuf:"varint,10,opt,name=max_value,json=maxValue,proto3" json:"max_value,omitempty"`
	MinValue         int32                  `protobuf:"varint,11,opt,name=min_value,json=minValue,proto3" json:"min_value,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PileConfig) Reset() {
	*x = PileConfig{}
	mi := &file_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PileConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PileConfig) ProtoMessage() {}

func (x *PileConfig) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PileConfig.ProtoReflect.Descriptor instead.
func (*PileConfig) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{2}
}

func (x *PileConfig) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PileConfig) GetSubpiles() []*PileConfig {
	if x != nil {
		return x.Subpiles
	}
	return nil
}

func (x *PileConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PileConfig) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PileConfig) GetUnitSingular() string {
	if x != nil {
		return x.UnitSingular
	}
	return ""
}

func (x *PileConfig) GetUnitPlural() string {
	if x != nil {
		return x.UnitPlural
	}
	return ""
}

func (x *PileConfig) GetUnitAbbreviation() string {
	if x != nil {
		return x.UnitAbbreviation
	}
	return ""
}

func (x *PileConfig) GetUnitAtomicScale() int32 {
	if x != nil {
		return x.UnitAtomicScale
	}
	return 0
}

func (x *PileConfig) GetInitialValue() int32 {
	if x != nil {
		return x.InitialValue
	}
	return 0
}

func (x *PileConfig) GetMaxValue() int32 {
	if x != nil {
		return x.MaxValue
	}
	return 0
}

func (x *PileConfig) GetMinValue() int32 {
	if x != nil {
		return x.MinValue
	}
	return 0
}

type PassiveTrigger struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Condition:
	//
	//	*PassiveTrigger_WeeklySchedule
	//	*PassiveTrigger_Interval
	Condition     isPassiveTrigger_Condition `protobuf_oneof:"condition"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PassiveTrigger) Reset() {
	*x = PassiveTrigger{}
	mi := &file_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PassiveTrigger) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PassiveTrigger) ProtoMessage() {}

func (x *PassiveTrigger) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PassiveTrigger.ProtoReflect.Descriptor instead.
func (*PassiveTrigger) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{3}
}

func (x *PassiveTrigger) GetCondition() isPassiveTrigger_Condition {
	if x != nil {
		return x.Condition
	}
	return nil
}

func (x *PassiveTrigger) GetWeeklySchedule() *TriggerWeeklySchedule {
	if x != nil {
		if x, ok := x.Condition.(*PassiveTrigger_WeeklySchedule); ok {
			return x.WeeklySchedule
		}
	}
	return nil
}

func (x *PassiveTrigger) GetInterval() *TriggerInterval {
	if x != nil {
		if x, ok := x.Condition.(*PassiveTrigger_Interval); ok {
			return x.Interval
		}
	}
	return nil
}

type isPassiveTrigger_Condition interface {
	isPassiveTrigger_Condition()
}

type PassiveTrigger_WeeklySchedule struct {
	WeeklySchedule *TriggerWeeklySchedule `protobuf:"bytes,1,opt,name=weekly_schedule,json=weeklySchedule,proto3,oneof"` // weekly schedule condition
}

type PassiveTrigger_Interval struct {
	Interval *TriggerInterval `protobuf:"bytes,2,opt,name=interval,proto3,oneof"` // time interval condition
}

func (*PassiveTrigger_WeeklySchedule) isPassiveTrigger_Condition() {}

func (*PassiveTrigger_Interval) isPassiveTrigger_Condition() {}

type PassivePipeline struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Trigger       []*PassiveTrigger      `protobuf:"bytes,1,rep,name=trigger,proto3" json:"trigger,omitempty"`
	Result        *Result                `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PassivePipeline) Reset() {
	*x = PassivePipeline{}
	mi := &file_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PassivePipeline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PassivePipeline) ProtoMessage() {}

func (x *PassivePipeline) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PassivePipeline.ProtoReflect.Descriptor instead.
func (*PassivePipeline) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{4}
}

func (x *PassivePipeline) GetTrigger() []*PassiveTrigger {
	if x != nil {
		return x.Trigger
	}
	return nil
}

func (x *PassivePipeline) GetResult() *Result {
	if x != nil {
		return x.Result
	}
	return nil
}

type NotificationConfig struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Method []NOTIFICATION_METHOD  `protobuf:"varint,1,rep,packed,name=method,proto3,enum=hometasker.v1.NOTIFICATION_METHOD" json:"method,omitempty"` // "gotify", "ntfy", etc.
	// for Gotify
	GotifyUrl   *string `protobuf:"bytes,2,opt,name=gotify_url,json=gotifyUrl,proto3,oneof" json:"gotify_url,omitempty"`
	GotifyToken *string `protobuf:"bytes,3,opt,name=gotify_token,json=gotifyToken,proto3,oneof" json:"gotify_token,omitempty"`
	// for email (only gmail supported)
	GmailUsername *string `protobuf:"bytes,4,opt,name=gmail_username,json=gmailUsername,proto3,oneof" json:"gmail_username,omitempty"`
	GmailPassword *string `protobuf:"bytes,5,opt,name=gmail_password,json=gmailPassword,proto3,oneof" json:"gmail_password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationConfig) Reset() {
	*x = NotificationConfig{}
	mi := &file_config_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationConfig) ProtoMessage() {}

func (x *NotificationConfig) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationConfig.ProtoReflect.Descriptor instead.
func (*NotificationConfig) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{5}
}

func (x *NotificationConfig) GetMethod() []NOTIFICATION_METHOD {
	if x != nil {
		return x.Method
	}
	return nil
}

func (x *NotificationConfig) GetGotifyUrl() string {
	if x != nil && x.GotifyUrl != nil {
		return *x.GotifyUrl
	}
	return ""
}

func (x *NotificationConfig) GetGotifyToken() string {
	if x != nil && x.GotifyToken != nil {
		return *x.GotifyToken
	}
	return ""
}

func (x *NotificationConfig) GetGmailUsername() string {
	if x != nil && x.GmailUsername != nil {
		return *x.GmailUsername
	}
	return ""
}

func (x *NotificationConfig) GetGmailPassword() string {
	if x != nil && x.GmailPassword != nil {
		return *x.GmailPassword
	}
	return ""
}

type MealConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecipePath    string                 `protobuf:"bytes,1,opt,name=recipe_path,json=recipePath,proto3" json:"recipe_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MealConfig) Reset() {
	*x = MealConfig{}
	mi := &file_config_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MealConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MealConfig) ProtoMessage() {}

func (x *MealConfig) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MealConfig.ProtoReflect.Descriptor instead.
func (*MealConfig) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{6}
}

func (x *MealConfig) GetRecipePath() string {
	if x != nil {
		return x.RecipePath
	}
	return ""
}

var File_config_proto protoreflect.FileDescriptor

const file_config_proto_rawDesc = "" +
	"\n" +
	"\fconfig.proto\x12\rhometasker.v1\x1a\vtasks.proto\"\xe7\x02\n" +
	"\x06Config\x12I\n" +
	"\x10passive_pipeline\x18\x01 \x03(\v2\x1e.hometasker.v1.PassivePipelineR\x0fpassivePipeline\x12<\n" +
	"\ftask_systems\x18\x02 \x03(\v2\x19.hometasker.v1.TaskSystemR\vtaskSystems\x12/\n" +
	"\x05piles\x18\x03 \x03(\v2\x19.hometasker.v1.PileConfigR\x05piles\x12)\n" +
	"\x05users\x18\x04 \x03(\v2\x13.hometasker.v1.UserR\x05users\x12G\n" +
	"\rnotifications\x18\x05 \x01(\v2!.hometasker.v1.NotificationConfigR\rnotifications\x12/\n" +
	"\x05meals\x18\x06 \x01(\v2\x19.hometasker.v1.MealConfigR\x05meals\"\x8d\x01\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x19\n" +
	"\x05phone\x18\x05 \x01(\tH\x00R\x05phone\x88\x01\x01B\b\n" +
	"\x06_phone\"\x87\x03\n" +
	"\n" +
	"PileConfig\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x125\n" +
	"\bsubpiles\x18\x02 \x03(\v2\x19.hometasker.v1.PileConfigR\bsubpiles\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12#\n" +
	"\runit_singular\x18\x05 \x01(\tR\funitSingular\x12\x1f\n" +
	"\vunit_plural\x18\x06 \x01(\tR\n" +
	"unitPlural\x12+\n" +
	"\x11unit_abbreviation\x18\a \x01(\tR\x10unitAbbreviation\x12*\n" +
	"\x11unit_atomic_scale\x18\b \x01(\x05R\x0funitAtomicScale\x12#\n" +
	"\rinitial_value\x18\t \x01(\x05R\finitialValue\x12\x1b\n" +
	"\tmax_value\x18\n" +
	" \x01(\x05R\bmaxValue\x12\x1b\n" +
	"\tmin_value\x18\v \x01(\x05R\bminValue\"\xac\x01\n" +
	"\x0ePassiveTrigger\x12O\n" +
	"\x0fweekly_schedule\x18\x01 \x01(\v2$.hometasker.v1.TriggerWeeklyScheduleH\x00R\x0eweeklySchedule\x12<\n" +
	"\binterval\x18\x02 \x01(\v2\x1e.hometasker.v1.TriggerIntervalH\x00R\bintervalB\v\n" +
	"\tcondition\"y\n" +
	"\x0fPassivePipeline\x127\n" +
	"\atrigger\x18\x01 \x03(\v2\x1d.hometasker.v1.PassiveTriggerR\atrigger\x12-\n" +
	"\x06result\x18\x02 \x01(\v2\x15.hometasker.v1.ResultR\x06result\"\xba\x02\n" +
	"\x12NotificationConfig\x12:\n" +
	"\x06method\x18\x01 \x03(\x0e2\".hometasker.v1.NOTIFICATION_METHODR\x06method\x12\"\n" +
	"\n" +
	"gotify_url\x18\x02 \x01(\tH\x00R\tgotifyUrl\x88\x01\x01\x12&\n" +
	"\fgotify_token\x18\x03 \x01(\tH\x01R\vgotifyToken\x88\x01\x01\x12*\n" +
	"\x0egmail_username\x18\x04 \x01(\tH\x02R\rgmailUsername\x88\x01\x01\x12*\n" +
	"\x0egmail_password\x18\x05 \x01(\tH\x03R\rgmailPassword\x88\x01\x01B\r\n" +
	"\v_gotify_urlB\x0f\n" +
	"\r_gotify_tokenB\x11\n" +
	"\x0f_gmail_usernameB\x11\n" +
	"\x0f_gmail_password\"-\n" +
	"\n" +
	"MealConfig\x12\x1f\n" +
	"\vrecipe_path\x18\x01 \x01(\tR\n" +
	"recipePath*Y\n" +
	"\x13NOTIFICATION_METHOD\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06GOTIFY\x10\x01\x12\b\n" +
	"\x04NTFY\x10\x02\x12\t\n" +
	"\x05EMAIL\x10\x03\x12\a\n" +
	"\x03SMS\x10\x04\x12\a\n" +
	"\x03LOG\x10\x05B\x0fZ\rhometasker/v1b\x06proto3"

var (
	file_config_proto_rawDescOnce sync.Once
	file_config_proto_rawDescData []byte
)

func file_config_proto_rawDescGZIP() []byte {
	file_config_proto_rawDescOnce.Do(func() {
		file_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_config_proto_rawDesc), len(file_config_proto_rawDesc)))
	})
	return file_config_proto_rawDescData
}

var file_config_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_config_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_config_proto_goTypes = []any{
	(NOTIFICATION_METHOD)(0),      // 0: hometasker.v1.NOTIFICATION_METHOD
	(*Config)(nil),                // 1: hometasker.v1.Config
	(*User)(nil),                  // 2: hometasker.v1.User
	(*PileConfig)(nil),            // 3: hometasker.v1.PileConfig
	(*PassiveTrigger)(nil),        // 4: hometasker.v1.PassiveTrigger
	(*PassivePipeline)(nil),       // 5: hometasker.v1.PassivePipeline
	(*NotificationConfig)(nil),    // 6: hometasker.v1.NotificationConfig
	(*MealConfig)(nil),            // 7: hometasker.v1.MealConfig
	(*TaskSystem)(nil),            // 8: hometasker.v1.TaskSystem
	(*TriggerWeeklySchedule)(nil), // 9: hometasker.v1.TriggerWeeklySchedule
	(*TriggerInterval)(nil),       // 10: hometasker.v1.TriggerInterval
	(*Result)(nil),                // 11: hometasker.v1.Result
}
var file_config_proto_depIdxs = []int32{
	5,  // 0: hometasker.v1.Config.passive_pipeline:type_name -> hometasker.v1.PassivePipeline
	8,  // 1: hometasker.v1.Config.task_systems:type_name -> hometasker.v1.TaskSystem
	3,  // 2: hometasker.v1.Config.piles:type_name -> hometasker.v1.PileConfig
	2,  // 3: hometasker.v1.Config.users:type_name -> hometasker.v1.User
	6,  // 4: hometasker.v1.Config.notifications:type_name -> hometasker.v1.NotificationConfig
	7,  // 5: hometasker.v1.Config.meals:type_name -> hometasker.v1.MealConfig
	3,  // 6: hometasker.v1.PileConfig.subpiles:type_name -> hometasker.v1.PileConfig
	9,  // 7: hometasker.v1.PassiveTrigger.weekly_schedule:type_name -> hometasker.v1.TriggerWeeklySchedule
	10, // 8: hometasker.v1.PassiveTrigger.interval:type_name -> hometasker.v1.TriggerInterval
	4,  // 9: hometasker.v1.PassivePipeline.trigger:type_name -> hometasker.v1.PassiveTrigger
	11, // 10: hometasker.v1.PassivePipeline.result:type_name -> hometasker.v1.Result
	0,  // 11: hometasker.v1.NotificationConfig.method:type_name -> hometasker.v1.NOTIFICATION_METHOD
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_config_proto_init() }
func file_config_proto_init() {
	if File_config_proto != nil {
		return
	}
	file_tasks_proto_init()
	file_config_proto_msgTypes[1].OneofWrappers = []any{}
	file_config_proto_msgTypes[3].OneofWrappers = []any{
		(*PassiveTrigger_WeeklySchedule)(nil),
		(*PassiveTrigger_Interval)(nil),
	}
	file_config_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_config_proto_rawDesc), len(file_config_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_config_proto_goTypes,
		DependencyIndexes: file_config_proto_depIdxs,
		EnumInfos:         file_config_proto_enumTypes,
		MessageInfos:      file_config_proto_msgTypes,
	}.Build()
	File_config_proto = out.File
	file_config_proto_goTypes = nil
	file_config_proto_depIdxs = nil
}
