// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: proto/inventory.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// UnitType defines the type of measurement unit
type UnitType int32

const (
	UnitType_UNIT_TYPE_UNSPECIFIED UnitType = 0
	UnitType_UNIT_TYPE_WEIGHT      UnitType = 1 // kg, lbs, grams, etc.
	UnitType_UNIT_TYPE_VOLUME      UnitType = 2 // liters, cups, gallons, etc.
	UnitType_UNIT_TYPE_COUNT       UnitType = 3 // items, pieces, etc.
	UnitType_UNIT_TYPE_LENGTH      UnitType = 4 // meters, feet, inches, etc.
	UnitType_UNIT_TYPE_AREA        UnitType = 5 // square meters, acres, etc.
)

// Enum value maps for UnitType.
var (
	UnitType_name = map[int32]string{
		0: "UNIT_TYPE_UNSPECIFIED",
		1: "UNIT_TYPE_WEIGHT",
		2: "UNIT_TYPE_VOLUME",
		3: "UNIT_TYPE_COUNT",
		4: "UNIT_TYPE_LENGTH",
		5: "UNIT_TYPE_AREA",
	}
	UnitType_value = map[string]int32{
		"UNIT_TYPE_UNSPECIFIED": 0,
		"UNIT_TYPE_WEIGHT":      1,
		"UNIT_TYPE_VOLUME":      2,
		"UNIT_TYPE_COUNT":       3,
		"UNIT_TYPE_LENGTH":      4,
		"UNIT_TYPE_AREA":        5,
	}
)

func (x UnitType) Enum() *UnitType {
	p := new(UnitType)
	*p = x
	return p
}

func (x UnitType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UnitType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_inventory_proto_enumTypes[0].Descriptor()
}

func (UnitType) Type() protoreflect.EnumType {
	return &file_proto_inventory_proto_enumTypes[0]
}

func (x UnitType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UnitType.Descriptor instead.
func (UnitType) EnumDescriptor() ([]byte, []int) {
	return file_proto_inventory_proto_rawDescGZIP(), []int{0}
}

// ConsumptionPattern defines how an item is typically consumed
type ConsumptionPattern int32

const (
	ConsumptionPattern_CONSUMPTION_PATTERN_UNSPECIFIED ConsumptionPattern = 0
	ConsumptionPattern_CONSUMPTION_PATTERN_LINEAR      ConsumptionPattern = 1 // Steady, consistent usage
	ConsumptionPattern_CONSUMPTION_PATTERN_SEASONAL    ConsumptionPattern = 2 // Varies by season/time of year
	ConsumptionPattern_CONSUMPTION_PATTERN_BATCH       ConsumptionPattern = 3 // Used in large amounts at once
	ConsumptionPattern_CONSUMPTION_PATTERN_RANDOM      ConsumptionPattern = 4 // Unpredictable usage
)

// Enum value maps for ConsumptionPattern.
var (
	ConsumptionPattern_name = map[int32]string{
		0: "CONSUMPTION_PATTERN_UNSPECIFIED",
		1: "CONSUMPTION_PATTERN_LINEAR",
		2: "CONSUMPTION_PATTERN_SEASONAL",
		3: "CONSUMPTION_PATTERN_BATCH",
		4: "CONSUMPTION_PATTERN_RANDOM",
	}
	ConsumptionPattern_value = map[string]int32{
		"CONSUMPTION_PATTERN_UNSPECIFIED": 0,
		"CONSUMPTION_PATTERN_LINEAR":      1,
		"CONSUMPTION_PATTERN_SEASONAL":    2,
		"CONSUMPTION_PATTERN_BATCH":       3,
		"CONSUMPTION_PATTERN_RANDOM":      4,
	}
)

func (x ConsumptionPattern) Enum() *ConsumptionPattern {
	p := new(ConsumptionPattern)
	*p = x
	return p
}

func (x ConsumptionPattern) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConsumptionPattern) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_inventory_proto_enumTypes[1].Descriptor()
}

func (ConsumptionPattern) Type() protoreflect.EnumType {
	return &file_proto_inventory_proto_enumTypes[1]
}

func (x ConsumptionPattern) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConsumptionPattern.Descriptor instead.
func (ConsumptionPattern) EnumDescriptor() ([]byte, []int) {
	return file_proto_inventory_proto_rawDescGZIP(), []int{1}
}

// Unit represents a measurement unit with conversion capabilities
type Unit struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                                     // Unique unit identifier (e.g., "kg", "lbs")
	Name                 string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                                                 // Human-readable name (e.g., "Kilograms")
	Symbol               string                 `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`                                                             // Display symbol (e.g., "kg")
	Type                 UnitType               `protobuf:"varint,4,opt,name=type,proto3,enum=inventory.v1.UnitType" json:"type,omitempty"`                                     // Type of measurement
	BaseConversionFactor float64                `protobuf:"fixed64,5,opt,name=base_conversion_factor,json=baseConversionFactor,proto3" json:"base_conversion_factor,omitempty"` // Factor to convert to base unit of this type
	BaseUnitId           string                 `protobuf:"bytes,6,opt,name=base_unit_id,json=baseUnitId,proto3" json:"base_unit_id,omitempty"`                                 // ID of the base unit for this type
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Unit) Reset() {
	*x = Unit{}
	mi := &file_proto_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Unit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Unit) ProtoMessage() {}

func (x *Unit) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Unit.ProtoReflect.Descriptor instead.
func (*Unit) Descriptor() ([]byte, []int) {
	return file_proto_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *Unit) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Unit) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Unit) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Unit) GetType() UnitType {
	if x != nil {
		return x.Type
	}
	return UnitType_UNIT_TYPE_UNSPECIFIED
}

func (x *Unit) GetBaseConversionFactor() float64 {
	if x != nil {
		return x.BaseConversionFactor
	}
	return 0
}

func (x *Unit) GetBaseUnitId() string {
	if x != nil {
		return x.BaseUnitId
	}
	return ""
}

// ConsumptionBehavior defines how an item is consumed over time
type ConsumptionBehavior struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Pattern           ConsumptionPattern     `protobuf:"varint,1,opt,name=pattern,proto3,enum=inventory.v1.ConsumptionPattern" json:"pattern,omitempty"`              // Type of consumption pattern
	AverageRatePerDay float64                `protobuf:"fixed64,2,opt,name=average_rate_per_day,json=averageRatePerDay,proto3" json:"average_rate_per_day,omitempty"` // Average consumption per day
	Variance          float64                `protobuf:"fixed64,3,opt,name=variance,proto3" json:"variance,omitempty"`                                                // Variance in consumption (for uncertainty)
	SeasonalFactors   []float64              `protobuf:"fixed64,4,rep,packed,name=seasonal_factors,json=seasonalFactors,proto3" json:"seasonal_factors,omitempty"`    // Monthly multipliers (12 values, Jan-Dec)
	LastUpdated       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ConsumptionBehavior) Reset() {
	*x = ConsumptionBehavior{}
	mi := &file_proto_inventory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumptionBehavior) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumptionBehavior) ProtoMessage() {}

func (x *ConsumptionBehavior) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumptionBehavior.ProtoReflect.Descriptor instead.
func (*ConsumptionBehavior) Descriptor() ([]byte, []int) {
	return file_proto_inventory_proto_rawDescGZIP(), []int{1}
}

func (x *ConsumptionBehavior) GetPattern() ConsumptionPattern {
	if x != nil {
		return x.Pattern
	}
	return ConsumptionPattern_CONSUMPTION_PATTERN_UNSPECIFIED
}

func (x *ConsumptionBehavior) GetAverageRatePerDay() float64 {
	if x != nil {
		return x.AverageRatePerDay
	}
	return 0
}

func (x *ConsumptionBehavior) GetVariance() float64 {
	if x != nil {
		return x.Variance
	}
	return 0
}

func (x *ConsumptionBehavior) GetSeasonalFactors() []float64 {
	if x != nil {
		return x.SeasonalFactors
	}
	return nil
}

func (x *ConsumptionBehavior) GetLastUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdated
	}
	return nil
}

// ConsumptionRecord tracks historical usage of an item
type ConsumptionRecord struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Timestamp      *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	AmountConsumed float64                `protobuf:"fixed64,2,opt,name=amount_consumed,json=amountConsumed,proto3" json:"amount_consumed,omitempty"`
	UnitId         string                 `protobuf:"bytes,3,opt,name=unit_id,json=unitId,proto3" json:"unit_id,omitempty"`
	Reason         string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"` // Optional: why item was consumed
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConsumptionRecord) Reset() {
	*x = ConsumptionRecord{}
	mi := &file_proto_inventory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumptionRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumptionRecord) ProtoMessage() {}

func (x *ConsumptionRecord) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumptionRecord.ProtoReflect.Descriptor instead.
func (*ConsumptionRecord) Descriptor() ([]byte, []int) {
	return file_proto_inventory_proto_rawDescGZIP(), []int{2}
}

func (x *ConsumptionRecord) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *ConsumptionRecord) GetAmountConsumed() float64 {
	if x != nil {
		return x.AmountConsumed
	}
	return 0
}

func (x *ConsumptionRecord) GetUnitId() string {
	if x != nil {
		return x.UnitId
	}
	return ""
}

func (x *ConsumptionRecord) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// InventoryItem represents a single item in inventory
type InventoryItem struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                            // Unique identifier
	Name                string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                                        // Human-readable name
	Description         string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`                                          // Optional description
	CurrentLevel        float64                `protobuf:"fixed64,4,opt,name=current_level,json=currentLevel,proto3" json:"current_level,omitempty"`                  // Current quantity available
	MaxCapacity         float64                `protobuf:"fixed64,5,opt,name=max_capacity,json=maxCapacity,proto3" json:"max_capacity,omitempty"`                     // Maximum storage capacity
	LowStockThreshold   float64                `protobuf:"fixed64,6,opt,name=low_stock_threshold,json=lowStockThreshold,proto3" json:"low_stock_threshold,omitempty"` // Alert when below this level
	UnitId              string                 `protobuf:"bytes,7,opt,name=unit_id,json=unitId,proto3" json:"unit_id,omitempty"`                                      // Primary unit for this item
	AlternateUnitIds    []string               `protobuf:"bytes,8,rep,name=alternate_unit_ids,json=alternateUnitIds,proto3" json:"alternate_unit_ids,omitempty"`      // Other valid units for this item
	ConsumptionBehavior *ConsumptionBehavior   `protobuf:"bytes,9,opt,name=consumption_behavior,json=consumptionBehavior,proto3" json:"consumption_behavior,omitempty"`
	ConsumptionHistory  []*ConsumptionRecord   `protobuf:"bytes,10,rep,name=consumption_history,json=consumptionHistory,proto3" json:"consumption_history,omitempty"`
	CreatedAt           *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt           *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Metadata            map[string]string      `protobuf:"bytes,13,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Custom key-value pairs
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *InventoryItem) Reset() {
	*x = InventoryItem{}
	mi := &file_proto_inventory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryItem) ProtoMessage() {}

func (x *InventoryItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryItem.ProtoReflect.Descriptor instead.
func (*InventoryItem) Descriptor() ([]byte, []int) {
	return file_proto_inventory_proto_rawDescGZIP(), []int{3}
}

func (x *InventoryItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InventoryItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InventoryItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *InventoryItem) GetCurrentLevel() float64 {
	if x != nil {
		return x.CurrentLevel
	}
	return 0
}

func (x *InventoryItem) GetMaxCapacity() float64 {
	if x != nil {
		return x.MaxCapacity
	}
	return 0
}

func (x *InventoryItem) GetLowStockThreshold() float64 {
	if x != nil {
		return x.LowStockThreshold
	}
	return 0
}

func (x *InventoryItem) GetUnitId() string {
	if x != nil {
		return x.UnitId
	}
	return ""
}

func (x *InventoryItem) GetAlternateUnitIds() []string {
	if x != nil {
		return x.AlternateUnitIds
	}
	return nil
}

func (x *InventoryItem) GetConsumptionBehavior() *ConsumptionBehavior {
	if x != nil {
		return x.ConsumptionBehavior
	}
	return nil
}

func (x *InventoryItem) GetConsumptionHistory() []*ConsumptionRecord {
	if x != nil {
		return x.ConsumptionHistory
	}
	return nil
}

func (x *InventoryItem) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *InventoryItem) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *InventoryItem) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// InventoryStatus provides overview of inventory state
type InventoryStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*InventoryItem       `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	LowStockItems []*InventoryItem       `protobuf:"bytes,2,rep,name=low_stock_items,json=lowStockItems,proto3" json:"low_stock_items,omitempty"`
	EmptyItems    []*InventoryItem       `protobuf:"bytes,3,rep,name=empty_items,json=emptyItems,proto3" json:"empty_items,omitempty"`
	TotalItems    int32                  `protobuf:"varint,4,opt,name=total_items,json=totalItems,proto3" json:"total_items,omitempty"`
	LastUpdated   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InventoryStatus) Reset() {
	*x = InventoryStatus{}
	mi := &file_proto_inventory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryStatus) ProtoMessage() {}

func (x *InventoryStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryStatus.ProtoReflect.Descriptor instead.
func (*InventoryStatus) Descriptor() ([]byte, []int) {
	return file_proto_inventory_proto_rawDescGZIP(), []int{4}
}

func (x *InventoryStatus) GetItems() []*InventoryItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *InventoryStatus) GetLowStockItems() []*InventoryItem {
	if x != nil {
		return x.LowStockItems
	}
	return nil
}

func (x *InventoryStatus) GetEmptyItems() []*InventoryItem {
	if x != nil {
		return x.EmptyItems
	}
	return nil
}

func (x *InventoryStatus) GetTotalItems() int32 {
	if x != nil {
		return x.TotalItems
	}
	return 0
}

func (x *InventoryStatus) GetLastUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdated
	}
	return nil
}

// ConsumptionPrediction provides forecasted usage for an item
type ConsumptionPrediction struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	ItemId                  string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	PredictedDaysRemaining  float64                `protobuf:"fixed64,2,opt,name=predicted_days_remaining,json=predictedDaysRemaining,proto3" json:"predicted_days_remaining,omitempty"` // How many days until empty
	ConfidenceScore         float64                `protobuf:"fixed64,3,opt,name=confidence_score,json=confidenceScore,proto3" json:"confidence_score,omitempty"`                        // 0.0 to 1.0, how confident we are
	PredictedEmptyDate      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=predicted_empty_date,json=predictedEmptyDate,proto3" json:"predicted_empty_date,omitempty"`
	RecommendedRestockLevel float64                `protobuf:"fixed64,5,opt,name=recommended_restock_level,json=recommendedRestockLevel,proto3" json:"recommended_restock_level,omitempty"` // Suggested amount to restock
	PredictionModel         string                 `protobuf:"bytes,6,opt,name=prediction_model,json=predictionModel,proto3" json:"prediction_model,omitempty"`                             // Which algorithm was used
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ConsumptionPrediction) Reset() {
	*x = ConsumptionPrediction{}
	mi := &file_proto_inventory_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumptionPrediction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumptionPrediction) ProtoMessage() {}

func (x *ConsumptionPrediction) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumptionPrediction.ProtoReflect.Descriptor instead.
func (*ConsumptionPrediction) Descriptor() ([]byte, []int) {
	return file_proto_inventory_proto_rawDescGZIP(), []int{5}
}

func (x *ConsumptionPrediction) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *ConsumptionPrediction) GetPredictedDaysRemaining() float64 {
	if x != nil {
		return x.PredictedDaysRemaining
	}
	return 0
}

func (x *ConsumptionPrediction) GetConfidenceScore() float64 {
	if x != nil {
		return x.ConfidenceScore
	}
	return 0
}

func (x *ConsumptionPrediction) GetPredictedEmptyDate() *timestamppb.Timestamp {
	if x != nil {
		return x.PredictedEmptyDate
	}
	return nil
}

func (x *ConsumptionPrediction) GetRecommendedRestockLevel() float64 {
	if x != nil {
		return x.RecommendedRestockLevel
	}
	return 0
}

func (x *ConsumptionPrediction) GetPredictionModel() string {
	if x != nil {
		return x.PredictionModel
	}
	return ""
}

// AddInventoryItemRequest creates a new inventory item
type AddInventoryItemRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Name              string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                                                                   // Required: item name
	Description       string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`                                                                     // Optional: item description
	InitialLevel      float64                `protobuf:"fixed64,3,opt,name=initial_level,json=initialLevel,proto3" json:"initial_level,omitempty"`                                             // Starting quantity
	MaxCapacity       float64                `protobuf:"fixed64,4,opt,name=max_capacity,json=maxCapacity,proto3" json:"max_capacity,omitempty"`                                                // Maximum storage capacity
	LowStockThreshold float64                `protobuf:"fixed64,5,opt,name=low_stock_threshold,json=lowStockThreshold,proto3" json:"low_stock_threshold,omitempty"`                            // Alert threshold
	UnitId            string                 `protobuf:"bytes,6,opt,name=unit_id,json=unitId,proto3" json:"unit_id,omitempty"`                                                                 // Primary unit
	Metadata          map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Custom properties
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AddInventoryItemRequest) Reset() {
	*x = AddInventoryItemRequest{}
	mi := &file_proto_inventory_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddInventoryItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddInventoryItemRequest) ProtoMessage() {}

func (x *AddInventoryItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddInventoryItemRequest.ProtoReflect.Descriptor instead.
func (*AddInventoryItemRequest) Descriptor() ([]byte, []int) {
	return file_proto_inventory_proto_rawDescGZIP(), []int{6}
}

func (x *AddInventoryItemRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddInventoryItemRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AddInventoryItemRequest) GetInitialLevel() float64 {
	if x != nil {
		return x.InitialLevel
	}
	return 0
}

func (x *AddInventoryItemRequest) GetMaxCapacity() float64 {
	if x != nil {
		return x.MaxCapacity
	}
	return 0
}

func (x *AddInventoryItemRequest) GetLowStockThreshold() float64 {
	if x != nil {
		return x.LowStockThreshold
	}
	return 0
}

func (x *AddInventoryItemRequest) GetUnitId() string {
	if x != nil {
		return x.UnitId
	}
	return ""
}

func (x *AddInventoryItemRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type AddInventoryItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *InventoryItem         `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddInventoryItemResponse) Reset() {
	*x = AddInventoryItemResponse{}
	mi := &file_proto_inventory_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddInventoryItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddInventoryItemResponse) ProtoMessage() {}

func (x *AddInventoryItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddInventoryItemResponse.ProtoReflect.Descriptor instead.
func (*AddInventoryItemResponse) Descriptor() ([]byte, []int) {
	return file_proto_inventory_proto_rawDescGZIP(), []int{7}
}

func (x *AddInventoryItemResponse) GetItem() *InventoryItem {
	if x != nil {
		return x.Item
	}
	return nil
}

// UpdateInventoryLevelRequest changes the quantity of an item
type UpdateInventoryLevelRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ItemId            string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`                                   // Required: item to update
	NewLevel          float64                `protobuf:"fixed64,2,opt,name=new_level,json=newLevel,proto3" json:"new_level,omitempty"`                           // New quantity level
	Reason            string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`                                                 // Optional: reason for change
	RecordConsumption bool                   `protobuf:"varint,4,opt,name=record_consumption,json=recordConsumption,proto3" json:"record_consumption,omitempty"` // Whether to record as consumption
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UpdateInventoryLevelRequest) Reset() {
	*x = UpdateInventoryLevelRequest{}
	mi := &file_proto_inventory_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateInventoryLevelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateInventoryLevelRequest) ProtoMessage() {}

func (x *UpdateInventoryLevelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateInventoryLevelRequest.ProtoReflect.Descriptor instead.
func (*UpdateInventoryLevelRequest) Descriptor() ([]byte, []int) {
	return file_proto_inventory_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateInventoryLevelRequest) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *UpdateInventoryLevelRequest) GetNewLevel() float64 {
	if x != nil {
		return x.NewLevel
	}
	return 0
}

func (x *UpdateInventoryLevelRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *UpdateInventoryLevelRequest) GetRecordConsumption() bool {
	if x != nil {
		return x.RecordConsumption
	}
	return false
}

type UpdateInventoryLevelResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Item           *InventoryItem         `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	LevelChanged   bool                   `protobuf:"varint,2,opt,name=level_changed,json=levelChanged,proto3" json:"level_changed,omitempty"`
	BelowThreshold bool                   `protobuf:"varint,3,opt,name=below_threshold,json=belowThreshold,proto3" json:"below_threshold,omitempty"` // Whether item is now below threshold
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateInventoryLevelResponse) Reset() {
	*x = UpdateInventoryLevelResponse{}
	mi := &file_proto_inventory_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateInventoryLevelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateInventoryLevelResponse) ProtoMessage() {}

func (x *UpdateInventoryLevelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateInventoryLevelResponse.ProtoReflect.Descriptor instead.
func (*UpdateInventoryLevelResponse) Descriptor() ([]byte, []int) {
	return file_proto_inventory_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateInventoryLevelResponse) GetItem() *InventoryItem {
	if x != nil {
		return x.Item
	}
	return nil
}

func (x *UpdateInventoryLevelResponse) GetLevelChanged() bool {
	if x != nil {
		return x.LevelChanged
	}
	return false
}

func (x *UpdateInventoryLevelResponse) GetBelowThreshold() bool {
	if x != nil {
		return x.BelowThreshold
	}
	return false
}

// GetInventoryStatusRequest retrieves overall inventory state
type GetInventoryStatusRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	IncludeLowStockOnly bool                   `protobuf:"varint,1,opt,name=include_low_stock_only,json=includeLowStockOnly,proto3" json:"include_low_stock_only,omitempty"` // Filter to only low stock items
	ItemIds             []string               `protobuf:"bytes,2,rep,name=item_ids,json=itemIds,proto3" json:"item_ids,omitempty"`                                          // Optional: filter to specific items
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetInventoryStatusRequest) Reset() {
	*x = GetInventoryStatusRequest{}
	mi := &file_proto_inventory_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInventoryStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInventoryStatusRequest) ProtoMessage() {}

func (x *GetInventoryStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInventoryStatusRequest.ProtoReflect.Descriptor instead.
func (*GetInventoryStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_inventory_proto_rawDescGZIP(), []int{10}
}

func (x *GetInventoryStatusRequest) GetIncludeLowStockOnly() bool {
	if x != nil {
		return x.IncludeLowStockOnly
	}
	return false
}

func (x *GetInventoryStatusRequest) GetItemIds() []string {
	if x != nil {
		return x.ItemIds
	}
	return nil
}

type GetInventoryStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *InventoryStatus       `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInventoryStatusResponse) Reset() {
	*x = GetInventoryStatusResponse{}
	mi := &file_proto_inventory_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInventoryStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInventoryStatusResponse) ProtoMessage() {}

func (x *GetInventoryStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInventoryStatusResponse.ProtoReflect.Descriptor instead.
func (*GetInventoryStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_inventory_proto_rawDescGZIP(), []int{11}
}

func (x *GetInventoryStatusResponse) GetStatus() *InventoryStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

// PredictConsumptionRequest generates usage forecasts
type PredictConsumptionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ItemId         string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`                          // Required: item to predict
	DaysAhead      int32                  `protobuf:"varint,2,opt,name=days_ahead,json=daysAhead,proto3" json:"days_ahead,omitempty"`                // How many days to forecast (default: 30)
	UpdateBehavior bool                   `protobuf:"varint,3,opt,name=update_behavior,json=updateBehavior,proto3" json:"update_behavior,omitempty"` // Whether to update consumption behavior
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PredictConsumptionRequest) Reset() {
	*x = PredictConsumptionRequest{}
	mi := &file_proto_inventory_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictConsumptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictConsumptionRequest) ProtoMessage() {}

func (x *PredictConsumptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictConsumptionRequest.ProtoReflect.Descriptor instead.
func (*PredictConsumptionRequest) Descriptor() ([]byte, []int) {
	return file_proto_inventory_proto_rawDescGZIP(), []int{12}
}

func (x *PredictConsumptionRequest) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *PredictConsumptionRequest) GetDaysAhead() int32 {
	if x != nil {
		return x.DaysAhead
	}
	return 0
}

func (x *PredictConsumptionRequest) GetUpdateBehavior() bool {
	if x != nil {
		return x.UpdateBehavior
	}
	return false
}

type PredictConsumptionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prediction    *ConsumptionPrediction `protobuf:"bytes,1,opt,name=prediction,proto3" json:"prediction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PredictConsumptionResponse) Reset() {
	*x = PredictConsumptionResponse{}
	mi := &file_proto_inventory_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictConsumptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictConsumptionResponse) ProtoMessage() {}

func (x *PredictConsumptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictConsumptionResponse.ProtoReflect.Descriptor instead.
func (*PredictConsumptionResponse) Descriptor() ([]byte, []int) {
	return file_proto_inventory_proto_rawDescGZIP(), []int{13}
}

func (x *PredictConsumptionResponse) GetPrediction() *ConsumptionPrediction {
	if x != nil {
		return x.Prediction
	}
	return nil
}

// SetConsumptionBehaviorRequest configures how an item is consumed
type SetConsumptionBehaviorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"` // Required: item to configure
	Behavior      *ConsumptionBehavior   `protobuf:"bytes,2,opt,name=behavior,proto3" json:"behavior,omitempty"`           // Consumption behavior settings
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetConsumptionBehaviorRequest) Reset() {
	*x = SetConsumptionBehaviorRequest{}
	mi := &file_proto_inventory_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetConsumptionBehaviorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetConsumptionBehaviorRequest) ProtoMessage() {}

func (x *SetConsumptionBehaviorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetConsumptionBehaviorRequest.ProtoReflect.Descriptor instead.
func (*SetConsumptionBehaviorRequest) Descriptor() ([]byte, []int) {
	return file_proto_inventory_proto_rawDescGZIP(), []int{14}
}

func (x *SetConsumptionBehaviorRequest) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *SetConsumptionBehaviorRequest) GetBehavior() *ConsumptionBehavior {
	if x != nil {
		return x.Behavior
	}
	return nil
}

type SetConsumptionBehaviorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *InventoryItem         `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetConsumptionBehaviorResponse) Reset() {
	*x = SetConsumptionBehaviorResponse{}
	mi := &file_proto_inventory_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetConsumptionBehaviorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetConsumptionBehaviorResponse) ProtoMessage() {}

func (x *SetConsumptionBehaviorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetConsumptionBehaviorResponse.ProtoReflect.Descriptor instead.
func (*SetConsumptionBehaviorResponse) Descriptor() ([]byte, []int) {
	return file_proto_inventory_proto_rawDescGZIP(), []int{15}
}

func (x *SetConsumptionBehaviorResponse) GetItem() *InventoryItem {
	if x != nil {
		return x.Item
	}
	return nil
}

// GetInventoryItemRequest retrieves a single item
type GetInventoryItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"` // Required: item identifier
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInventoryItemRequest) Reset() {
	*x = GetInventoryItemRequest{}
	mi := &file_proto_inventory_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInventoryItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInventoryItemRequest) ProtoMessage() {}

func (x *GetInventoryItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInventoryItemRequest.ProtoReflect.Descriptor instead.
func (*GetInventoryItemRequest) Descriptor() ([]byte, []int) {
	return file_proto_inventory_proto_rawDescGZIP(), []int{16}
}

func (x *GetInventoryItemRequest) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

type GetInventoryItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *InventoryItem         `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInventoryItemResponse) Reset() {
	*x = GetInventoryItemResponse{}
	mi := &file_proto_inventory_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInventoryItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInventoryItemResponse) ProtoMessage() {}

func (x *GetInventoryItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInventoryItemResponse.ProtoReflect.Descriptor instead.
func (*GetInventoryItemResponse) Descriptor() ([]byte, []int) {
	return file_proto_inventory_proto_rawDescGZIP(), []int{17}
}

func (x *GetInventoryItemResponse) GetItem() *InventoryItem {
	if x != nil {
		return x.Item
	}
	return nil
}

// ListInventoryItemsRequest retrieves filtered list of items
type ListInventoryItemsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	LowStockOnly   bool                   `protobuf:"varint,1,opt,name=low_stock_only,json=lowStockOnly,proto3" json:"low_stock_only,omitempty"`      // Filter to low stock items
	UnitTypeFilter string                 `protobuf:"bytes,2,opt,name=unit_type_filter,json=unitTypeFilter,proto3" json:"unit_type_filter,omitempty"` // Filter by unit type
	Limit          int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`                                          // Maximum items to return
	Offset         int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`                                        // Pagination offset
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListInventoryItemsRequest) Reset() {
	*x = ListInventoryItemsRequest{}
	mi := &file_proto_inventory_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInventoryItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInventoryItemsRequest) ProtoMessage() {}

func (x *ListInventoryItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInventoryItemsRequest.ProtoReflect.Descriptor instead.
func (*ListInventoryItemsRequest) Descriptor() ([]byte, []int) {
	return file_proto_inventory_proto_rawDescGZIP(), []int{18}
}

func (x *ListInventoryItemsRequest) GetLowStockOnly() bool {
	if x != nil {
		return x.LowStockOnly
	}
	return false
}

func (x *ListInventoryItemsRequest) GetUnitTypeFilter() string {
	if x != nil {
		return x.UnitTypeFilter
	}
	return ""
}

func (x *ListInventoryItemsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListInventoryItemsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListInventoryItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*InventoryItem       `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"` // Total items matching filter
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInventoryItemsResponse) Reset() {
	*x = ListInventoryItemsResponse{}
	mi := &file_proto_inventory_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInventoryItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInventoryItemsResponse) ProtoMessage() {}

func (x *ListInventoryItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInventoryItemsResponse.ProtoReflect.Descriptor instead.
func (*ListInventoryItemsResponse) Descriptor() ([]byte, []int) {
	return file_proto_inventory_proto_rawDescGZIP(), []int{19}
}

func (x *ListInventoryItemsResponse) GetItems() []*InventoryItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListInventoryItemsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// ConvertUnitsRequest converts quantities between units
type ConvertUnitsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        float64                `protobuf:"fixed64,1,opt,name=amount,proto3" json:"amount,omitempty"`                           // Quantity to convert
	FromUnitId    string                 `protobuf:"bytes,2,opt,name=from_unit_id,json=fromUnitId,proto3" json:"from_unit_id,omitempty"` // Source unit
	ToUnitId      string                 `protobuf:"bytes,3,opt,name=to_unit_id,json=toUnitId,proto3" json:"to_unit_id,omitempty"`       // Target unit
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConvertUnitsRequest) Reset() {
	*x = ConvertUnitsRequest{}
	mi := &file_proto_inventory_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvertUnitsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertUnitsRequest) ProtoMessage() {}

func (x *ConvertUnitsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvertUnitsRequest.ProtoReflect.Descriptor instead.
func (*ConvertUnitsRequest) Descriptor() ([]byte, []int) {
	return file_proto_inventory_proto_rawDescGZIP(), []int{20}
}

func (x *ConvertUnitsRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ConvertUnitsRequest) GetFromUnitId() string {
	if x != nil {
		return x.FromUnitId
	}
	return ""
}

func (x *ConvertUnitsRequest) GetToUnitId() string {
	if x != nil {
		return x.ToUnitId
	}
	return ""
}

type ConvertUnitsResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ConvertedAmount    float64                `protobuf:"fixed64,1,opt,name=converted_amount,json=convertedAmount,proto3" json:"converted_amount,omitempty"`         // Result of conversion
	ConversionPossible bool                   `protobuf:"varint,2,opt,name=conversion_possible,json=conversionPossible,proto3" json:"conversion_possible,omitempty"` // Whether conversion was possible
	ErrorMessage       string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`                    // Error if conversion failed
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ConvertUnitsResponse) Reset() {
	*x = ConvertUnitsResponse{}
	mi := &file_proto_inventory_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvertUnitsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertUnitsResponse) ProtoMessage() {}

func (x *ConvertUnitsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvertUnitsResponse.ProtoReflect.Descriptor instead.
func (*ConvertUnitsResponse) Descriptor() ([]byte, []int) {
	return file_proto_inventory_proto_rawDescGZIP(), []int{21}
}

func (x *ConvertUnitsResponse) GetConvertedAmount() float64 {
	if x != nil {
		return x.ConvertedAmount
	}
	return 0
}

func (x *ConvertUnitsResponse) GetConversionPossible() bool {
	if x != nil {
		return x.ConversionPossible
	}
	return false
}

func (x *ConvertUnitsResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_proto_inventory_proto protoreflect.FileDescriptor

const file_proto_inventory_proto_rawDesc = "" +
	"\n" +
	"\x15proto/inventory.proto\x12\finventory.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc6\x01\n" +
	"\x04Unit\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06symbol\x18\x03 \x01(\tR\x06symbol\x12*\n" +
	"\x04type\x18\x04 \x01(\x0e2\x16.inventory.v1.UnitTypeR\x04type\x124\n" +
	"\x16base_conversion_factor\x18\x05 \x01(\x01R\x14baseConversionFactor\x12 \n" +
	"\fbase_unit_id\x18\x06 \x01(\tR\n" +
	"baseUnitId\"\x88\x02\n" +
	"\x13ConsumptionBehavior\x12:\n" +
	"\apattern\x18\x01 \x01(\x0e2 .inventory.v1.ConsumptionPatternR\apattern\x12/\n" +
	"\x14average_rate_per_day\x18\x02 \x01(\x01R\x11averageRatePerDay\x12\x1a\n" +
	"\bvariance\x18\x03 \x01(\x01R\bvariance\x12)\n" +
	"\x10seasonal_factors\x18\x04 \x03(\x01R\x0fseasonalFactors\x12=\n" +
	"\flast_updated\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vlastUpdated\"\xa7\x01\n" +
	"\x11ConsumptionRecord\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12'\n" +
	"\x0famount_consumed\x18\x02 \x01(\x01R\x0eamountConsumed\x12\x17\n" +
	"\aunit_id\x18\x03 \x01(\tR\x06unitId\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"\xb6\x05\n" +
	"\rInventoryItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12#\n" +
	"\rcurrent_level\x18\x04 \x01(\x01R\fcurrentLevel\x12!\n" +
	"\fmax_capacity\x18\x05 \x01(\x01R\vmaxCapacity\x12.\n" +
	"\x13low_stock_threshold\x18\x06 \x01(\x01R\x11lowStockThreshold\x12\x17\n" +
	"\aunit_id\x18\a \x01(\tR\x06unitId\x12,\n" +
	"\x12alternate_unit_ids\x18\b \x03(\tR\x10alternateUnitIds\x12T\n" +
	"\x14consumption_behavior\x18\t \x01(\v2!.inventory.v1.ConsumptionBehaviorR\x13consumptionBehavior\x12P\n" +
	"\x13consumption_history\x18\n" +
	" \x03(\v2\x1f.inventory.v1.ConsumptionRecordR\x12consumptionHistory\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12E\n" +
	"\bmetadata\x18\r \x03(\v2).inventory.v1.InventoryItem.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa7\x02\n" +
	"\x0fInventoryStatus\x121\n" +
	"\x05items\x18\x01 \x03(\v2\x1b.inventory.v1.InventoryItemR\x05items\x12C\n" +
	"\x0flow_stock_items\x18\x02 \x03(\v2\x1b.inventory.v1.InventoryItemR\rlowStockItems\x12<\n" +
	"\vempty_items\x18\x03 \x03(\v2\x1b.inventory.v1.InventoryItemR\n" +
	"emptyItems\x12\x1f\n" +
	"\vtotal_items\x18\x04 \x01(\x05R\n" +
	"totalItems\x12=\n" +
	"\flast_updated\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vlastUpdated\"\xca\x02\n" +
	"\x15ConsumptionPrediction\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x128\n" +
	"\x18predicted_days_remaining\x18\x02 \x01(\x01R\x16predictedDaysRemaining\x12)\n" +
	"\x10confidence_score\x18\x03 \x01(\x01R\x0fconfidenceScore\x12L\n" +
	"\x14predicted_empty_date\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x12predictedEmptyDate\x12:\n" +
	"\x19recommended_restock_level\x18\x05 \x01(\x01R\x17recommendedRestockLevel\x12)\n" +
	"\x10prediction_model\x18\x06 \x01(\tR\x0fpredictionModel\"\xee\x02\n" +
	"\x17AddInventoryItemRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12#\n" +
	"\rinitial_level\x18\x03 \x01(\x01R\finitialLevel\x12!\n" +
	"\fmax_capacity\x18\x04 \x01(\x01R\vmaxCapacity\x12.\n" +
	"\x13low_stock_threshold\x18\x05 \x01(\x01R\x11lowStockThreshold\x12\x17\n" +
	"\aunit_id\x18\x06 \x01(\tR\x06unitId\x12O\n" +
	"\bmetadata\x18\a \x03(\v23.inventory.v1.AddInventoryItemRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"K\n" +
	"\x18AddInventoryItemResponse\x12/\n" +
	"\x04item\x18\x01 \x01(\v2\x1b.inventory.v1.InventoryItemR\x04item\"\x9a\x01\n" +
	"\x1bUpdateInventoryLevelRequest\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12\x1b\n" +
	"\tnew_level\x18\x02 \x01(\x01R\bnewLevel\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12-\n" +
	"\x12record_consumption\x18\x04 \x01(\bR\x11recordConsumption\"\x9d\x01\n" +
	"\x1cUpdateInventoryLevelResponse\x12/\n" +
	"\x04item\x18\x01 \x01(\v2\x1b.inventory.v1.InventoryItemR\x04item\x12#\n" +
	"\rlevel_changed\x18\x02 \x01(\bR\flevelChanged\x12'\n" +
	"\x0fbelow_threshold\x18\x03 \x01(\bR\x0ebelowThreshold\"k\n" +
	"\x19GetInventoryStatusRequest\x123\n" +
	"\x16include_low_stock_only\x18\x01 \x01(\bR\x13includeLowStockOnly\x12\x19\n" +
	"\bitem_ids\x18\x02 \x03(\tR\aitemIds\"S\n" +
	"\x1aGetInventoryStatusResponse\x125\n" +
	"\x06status\x18\x01 \x01(\v2\x1d.inventory.v1.InventoryStatusR\x06status\"|\n" +
	"\x19PredictConsumptionRequest\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12\x1d\n" +
	"\n" +
	"days_ahead\x18\x02 \x01(\x05R\tdaysAhead\x12'\n" +
	"\x0fupdate_behavior\x18\x03 \x01(\bR\x0eupdateBehavior\"a\n" +
	"\x1aPredictConsumptionResponse\x12C\n" +
	"\n" +
	"prediction\x18\x01 \x01(\v2#.inventory.v1.ConsumptionPredictionR\n" +
	"prediction\"w\n" +
	"\x1dSetConsumptionBehaviorRequest\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12=\n" +
	"\bbehavior\x18\x02 \x01(\v2!.inventory.v1.ConsumptionBehaviorR\bbehavior\"Q\n" +
	"\x1eSetConsumptionBehaviorResponse\x12/\n" +
	"\x04item\x18\x01 \x01(\v2\x1b.inventory.v1.InventoryItemR\x04item\"2\n" +
	"\x17GetInventoryItemRequest\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\"K\n" +
	"\x18GetInventoryItemResponse\x12/\n" +
	"\x04item\x18\x01 \x01(\v2\x1b.inventory.v1.InventoryItemR\x04item\"\x99\x01\n" +
	"\x19ListInventoryItemsRequest\x12$\n" +
	"\x0elow_stock_only\x18\x01 \x01(\bR\flowStockOnly\x12(\n" +
	"\x10unit_type_filter\x18\x02 \x01(\tR\x0eunitTypeFilter\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\"p\n" +
	"\x1aListInventoryItemsResponse\x121\n" +
	"\x05items\x18\x01 \x03(\v2\x1b.inventory.v1.InventoryItemR\x05items\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"m\n" +
	"\x13ConvertUnitsRequest\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x01R\x06amount\x12 \n" +
	"\ffrom_unit_id\x18\x02 \x01(\tR\n" +
	"fromUnitId\x12\x1c\n" +
	"\n" +
	"to_unit_id\x18\x03 \x01(\tR\btoUnitId\"\x97\x01\n" +
	"\x14ConvertUnitsResponse\x12)\n" +
	"\x10converted_amount\x18\x01 \x01(\x01R\x0fconvertedAmount\x12/\n" +
	"\x13conversion_possible\x18\x02 \x01(\bR\x12conversionPossible\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage*\x90\x01\n" +
	"\bUnitType\x12\x19\n" +
	"\x15UNIT_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10UNIT_TYPE_WEIGHT\x10\x01\x12\x14\n" +
	"\x10UNIT_TYPE_VOLUME\x10\x02\x12\x13\n" +
	"\x0fUNIT_TYPE_COUNT\x10\x03\x12\x14\n" +
	"\x10UNIT_TYPE_LENGTH\x10\x04\x12\x12\n" +
	"\x0eUNIT_TYPE_AREA\x10\x05*\xba\x01\n" +
	"\x12ConsumptionPattern\x12#\n" +
	"\x1fCONSUMPTION_PATTERN_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aCONSUMPTION_PATTERN_LINEAR\x10\x01\x12 \n" +
	"\x1cCONSUMPTION_PATTERN_SEASONAL\x10\x02\x12\x1d\n" +
	"\x19CONSUMPTION_PATTERN_BATCH\x10\x03\x12\x1e\n" +
	"\x1aCONSUMPTION_PATTERN_RANDOM\x10\x042\xce\x06\n" +
	"\x10InventoryService\x12a\n" +
	"\x10AddInventoryItem\x12%.inventory.v1.AddInventoryItemRequest\x1a&.inventory.v1.AddInventoryItemResponse\x12a\n" +
	"\x10GetInventoryItem\x12%.inventory.v1.GetInventoryItemRequest\x1a&.inventory.v1.GetInventoryItemResponse\x12g\n" +
	"\x12ListInventoryItems\x12'.inventory.v1.ListInventoryItemsRequest\x1a(.inventory.v1.ListInventoryItemsResponse\x12m\n" +
	"\x14UpdateInventoryLevel\x12).inventory.v1.UpdateInventoryLevelRequest\x1a*.inventory.v1.UpdateInventoryLevelResponse\x12g\n" +
	"\x12GetInventoryStatus\x12'.inventory.v1.GetInventoryStatusRequest\x1a(.inventory.v1.GetInventoryStatusResponse\x12g\n" +
	"\x12PredictConsumption\x12'.inventory.v1.PredictConsumptionRequest\x1a(.inventory.v1.PredictConsumptionResponse\x12s\n" +
	"\x16SetConsumptionBehavior\x12+.inventory.v1.SetConsumptionBehaviorRequest\x1a,.inventory.v1.SetConsumptionBehaviorResponse\x12U\n" +
	"\fConvertUnits\x12!.inventory.v1.ConvertUnitsRequest\x1a\".inventory.v1.ConvertUnitsResponseBDZBgithub.com/DaDevFox/task-systems/inventory-core/proto/inventory/v1b\x06proto3"

var (
	file_proto_inventory_proto_rawDescOnce sync.Once
	file_proto_inventory_proto_rawDescData []byte
)

func file_proto_inventory_proto_rawDescGZIP() []byte {
	file_proto_inventory_proto_rawDescOnce.Do(func() {
		file_proto_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_inventory_proto_rawDesc), len(file_proto_inventory_proto_rawDesc)))
	})
	return file_proto_inventory_proto_rawDescData
}

var file_proto_inventory_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_proto_inventory_proto_goTypes = []any{
	(UnitType)(0),                          // 0: inventory.v1.UnitType
	(ConsumptionPattern)(0),                // 1: inventory.v1.ConsumptionPattern
	(*Unit)(nil),                           // 2: inventory.v1.Unit
	(*ConsumptionBehavior)(nil),            // 3: inventory.v1.ConsumptionBehavior
	(*ConsumptionRecord)(nil),              // 4: inventory.v1.ConsumptionRecord
	(*InventoryItem)(nil),                  // 5: inventory.v1.InventoryItem
	(*InventoryStatus)(nil),                // 6: inventory.v1.InventoryStatus
	(*ConsumptionPrediction)(nil),          // 7: inventory.v1.ConsumptionPrediction
	(*AddInventoryItemRequest)(nil),        // 8: inventory.v1.AddInventoryItemRequest
	(*AddInventoryItemResponse)(nil),       // 9: inventory.v1.AddInventoryItemResponse
	(*UpdateInventoryLevelRequest)(nil),    // 10: inventory.v1.UpdateInventoryLevelRequest
	(*UpdateInventoryLevelResponse)(nil),   // 11: inventory.v1.UpdateInventoryLevelResponse
	(*GetInventoryStatusRequest)(nil),      // 12: inventory.v1.GetInventoryStatusRequest
	(*GetInventoryStatusResponse)(nil),     // 13: inventory.v1.GetInventoryStatusResponse
	(*PredictConsumptionRequest)(nil),      // 14: inventory.v1.PredictConsumptionRequest
	(*PredictConsumptionResponse)(nil),     // 15: inventory.v1.PredictConsumptionResponse
	(*SetConsumptionBehaviorRequest)(nil),  // 16: inventory.v1.SetConsumptionBehaviorRequest
	(*SetConsumptionBehaviorResponse)(nil), // 17: inventory.v1.SetConsumptionBehaviorResponse
	(*GetInventoryItemRequest)(nil),        // 18: inventory.v1.GetInventoryItemRequest
	(*GetInventoryItemResponse)(nil),       // 19: inventory.v1.GetInventoryItemResponse
	(*ListInventoryItemsRequest)(nil),      // 20: inventory.v1.ListInventoryItemsRequest
	(*ListInventoryItemsResponse)(nil),     // 21: inventory.v1.ListInventoryItemsResponse
	(*ConvertUnitsRequest)(nil),            // 22: inventory.v1.ConvertUnitsRequest
	(*ConvertUnitsResponse)(nil),           // 23: inventory.v1.ConvertUnitsResponse
	nil,                                    // 24: inventory.v1.InventoryItem.MetadataEntry
	nil,                                    // 25: inventory.v1.AddInventoryItemRequest.MetadataEntry
	(*timestamppb.Timestamp)(nil),          // 26: google.protobuf.Timestamp
}
var file_proto_inventory_proto_depIdxs = []int32{
	0,  // 0: inventory.v1.Unit.type:type_name -> inventory.v1.UnitType
	1,  // 1: inventory.v1.ConsumptionBehavior.pattern:type_name -> inventory.v1.ConsumptionPattern
	26, // 2: inventory.v1.ConsumptionBehavior.last_updated:type_name -> google.protobuf.Timestamp
	26, // 3: inventory.v1.ConsumptionRecord.timestamp:type_name -> google.protobuf.Timestamp
	3,  // 4: inventory.v1.InventoryItem.consumption_behavior:type_name -> inventory.v1.ConsumptionBehavior
	4,  // 5: inventory.v1.InventoryItem.consumption_history:type_name -> inventory.v1.ConsumptionRecord
	26, // 6: inventory.v1.InventoryItem.created_at:type_name -> google.protobuf.Timestamp
	26, // 7: inventory.v1.InventoryItem.updated_at:type_name -> google.protobuf.Timestamp
	24, // 8: inventory.v1.InventoryItem.metadata:type_name -> inventory.v1.InventoryItem.MetadataEntry
	5,  // 9: inventory.v1.InventoryStatus.items:type_name -> inventory.v1.InventoryItem
	5,  // 10: inventory.v1.InventoryStatus.low_stock_items:type_name -> inventory.v1.InventoryItem
	5,  // 11: inventory.v1.InventoryStatus.empty_items:type_name -> inventory.v1.InventoryItem
	26, // 12: inventory.v1.InventoryStatus.last_updated:type_name -> google.protobuf.Timestamp
	26, // 13: inventory.v1.ConsumptionPrediction.predicted_empty_date:type_name -> google.protobuf.Timestamp
	25, // 14: inventory.v1.AddInventoryItemRequest.metadata:type_name -> inventory.v1.AddInventoryItemRequest.MetadataEntry
	5,  // 15: inventory.v1.AddInventoryItemResponse.item:type_name -> inventory.v1.InventoryItem
	5,  // 16: inventory.v1.UpdateInventoryLevelResponse.item:type_name -> inventory.v1.InventoryItem
	6,  // 17: inventory.v1.GetInventoryStatusResponse.status:type_name -> inventory.v1.InventoryStatus
	7,  // 18: inventory.v1.PredictConsumptionResponse.prediction:type_name -> inventory.v1.ConsumptionPrediction
	3,  // 19: inventory.v1.SetConsumptionBehaviorRequest.behavior:type_name -> inventory.v1.ConsumptionBehavior
	5,  // 20: inventory.v1.SetConsumptionBehaviorResponse.item:type_name -> inventory.v1.InventoryItem
	5,  // 21: inventory.v1.GetInventoryItemResponse.item:type_name -> inventory.v1.InventoryItem
	5,  // 22: inventory.v1.ListInventoryItemsResponse.items:type_name -> inventory.v1.InventoryItem
	8,  // 23: inventory.v1.InventoryService.AddInventoryItem:input_type -> inventory.v1.AddInventoryItemRequest
	18, // 24: inventory.v1.InventoryService.GetInventoryItem:input_type -> inventory.v1.GetInventoryItemRequest
	20, // 25: inventory.v1.InventoryService.ListInventoryItems:input_type -> inventory.v1.ListInventoryItemsRequest
	10, // 26: inventory.v1.InventoryService.UpdateInventoryLevel:input_type -> inventory.v1.UpdateInventoryLevelRequest
	12, // 27: inventory.v1.InventoryService.GetInventoryStatus:input_type -> inventory.v1.GetInventoryStatusRequest
	14, // 28: inventory.v1.InventoryService.PredictConsumption:input_type -> inventory.v1.PredictConsumptionRequest
	16, // 29: inventory.v1.InventoryService.SetConsumptionBehavior:input_type -> inventory.v1.SetConsumptionBehaviorRequest
	22, // 30: inventory.v1.InventoryService.ConvertUnits:input_type -> inventory.v1.ConvertUnitsRequest
	9,  // 31: inventory.v1.InventoryService.AddInventoryItem:output_type -> inventory.v1.AddInventoryItemResponse
	19, // 32: inventory.v1.InventoryService.GetInventoryItem:output_type -> inventory.v1.GetInventoryItemResponse
	21, // 33: inventory.v1.InventoryService.ListInventoryItems:output_type -> inventory.v1.ListInventoryItemsResponse
	11, // 34: inventory.v1.InventoryService.UpdateInventoryLevel:output_type -> inventory.v1.UpdateInventoryLevelResponse
	13, // 35: inventory.v1.InventoryService.GetInventoryStatus:output_type -> inventory.v1.GetInventoryStatusResponse
	15, // 36: inventory.v1.InventoryService.PredictConsumption:output_type -> inventory.v1.PredictConsumptionResponse
	17, // 37: inventory.v1.InventoryService.SetConsumptionBehavior:output_type -> inventory.v1.SetConsumptionBehaviorResponse
	23, // 38: inventory.v1.InventoryService.ConvertUnits:output_type -> inventory.v1.ConvertUnitsResponse
	31, // [31:39] is the sub-list for method output_type
	23, // [23:31] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_proto_inventory_proto_init() }
func file_proto_inventory_proto_init() {
	if File_proto_inventory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_inventory_proto_rawDesc), len(file_proto_inventory_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_inventory_proto_goTypes,
		DependencyIndexes: file_proto_inventory_proto_depIdxs,
		EnumInfos:         file_proto_inventory_proto_enumTypes,
		MessageInfos:      file_proto_inventory_proto_msgTypes,
	}.Build()
	File_proto_inventory_proto = out.File
	file_proto_inventory_proto_goTypes = nil
	file_proto_inventory_proto_depIdxs = nil
}
