version: "3.8"

services:
  task-server:
    build: .
    container_name: task-management-server
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8080"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    restart: unless-stopped
    networks:
      - task-network

networks:
  task-network:
    driver: bridge

volumes:
  task-data:
    driver: local
