worker_processes auto;

events {
    worker_connections 1024;
}

http {
    upstream user_core {
        server user-core:50051;
    }

    upstream inventory_core {
        server inventory-core:50052;
    }

    upstream tasker_core {
        server tasker-core:50053;
    }

    server {
        listen 50050 http2;

        location /usercore.v1.UserService/ {
            grpc_pass grpc://user_core;
        }

        location /inventory.v1.InventoryService/ {
            grpc_pass grpc://inventory_core;
        }

        location /taskcore.v1.TaskService/ {
            grpc_pass grpc://tasker_core;
        }
    }
}
