// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/hometasker_service.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MarkTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          string                 `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	User          string                 `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkTaskRequest) Reset() {
	*x = MarkTaskRequest{}
	mi := &file_proto_hometasker_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkTaskRequest) ProtoMessage() {}

func (x *MarkTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hometasker_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkTaskRequest.ProtoReflect.Descriptor instead.
func (*MarkTaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_hometasker_service_proto_rawDescGZIP(), []int{0}
}

func (x *MarkTaskRequest) GetTask() string {
	if x != nil {
		return x.Task
	}
	return ""
}

func (x *MarkTaskRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

type MarkTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkTaskResponse) Reset() {
	*x = MarkTaskResponse{}
	mi := &file_proto_hometasker_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkTaskResponse) ProtoMessage() {}

func (x *MarkTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hometasker_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkTaskResponse.ProtoReflect.Descriptor instead.
func (*MarkTaskResponse) Descriptor() ([]byte, []int) {
	return file_proto_hometasker_service_proto_rawDescGZIP(), []int{1}
}

type MarkReviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          string                 `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	Reviewer      string                 `protobuf:"bytes,2,opt,name=reviewer,proto3" json:"reviewer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkReviewRequest) Reset() {
	*x = MarkReviewRequest{}
	mi := &file_proto_hometasker_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkReviewRequest) ProtoMessage() {}

func (x *MarkReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hometasker_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkReviewRequest.ProtoReflect.Descriptor instead.
func (*MarkReviewRequest) Descriptor() ([]byte, []int) {
	return file_proto_hometasker_service_proto_rawDescGZIP(), []int{2}
}

func (x *MarkReviewRequest) GetTask() string {
	if x != nil {
		return x.Task
	}
	return ""
}

func (x *MarkReviewRequest) GetReviewer() string {
	if x != nil {
		return x.Reviewer
	}
	return ""
}

type MarkReviewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkReviewResponse) Reset() {
	*x = MarkReviewResponse{}
	mi := &file_proto_hometasker_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkReviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkReviewResponse) ProtoMessage() {}

func (x *MarkReviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hometasker_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkReviewResponse.ProtoReflect.Descriptor instead.
func (*MarkReviewResponse) Descriptor() ([]byte, []int) {
	return file_proto_hometasker_service_proto_rawDescGZIP(), []int{3}
}

type AddPileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PileId        string                 `protobuf:"bytes,1,opt,name=pile_id,json=pileId,proto3" json:"pile_id,omitempty"`
	Delta         int32                  `protobuf:"varint,2,opt,name=delta,proto3" json:"delta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddPileRequest) Reset() {
	*x = AddPileRequest{}
	mi := &file_proto_hometasker_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPileRequest) ProtoMessage() {}

func (x *AddPileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hometasker_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPileRequest.ProtoReflect.Descriptor instead.
func (*AddPileRequest) Descriptor() ([]byte, []int) {
	return file_proto_hometasker_service_proto_rawDescGZIP(), []int{4}
}

func (x *AddPileRequest) GetPileId() string {
	if x != nil {
		return x.PileId
	}
	return ""
}

func (x *AddPileRequest) GetDelta() int32 {
	if x != nil {
		return x.Delta
	}
	return 0
}

type AddPileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddPileResponse) Reset() {
	*x = AddPileResponse{}
	mi := &file_proto_hometasker_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPileResponse) ProtoMessage() {}

func (x *AddPileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hometasker_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPileResponse.ProtoReflect.Descriptor instead.
func (*AddPileResponse) Descriptor() ([]byte, []int) {
	return file_proto_hometasker_service_proto_rawDescGZIP(), []int{5}
}

type LeaderboardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaderboardRequest) Reset() {
	*x = LeaderboardRequest{}
	mi := &file_proto_hometasker_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderboardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderboardRequest) ProtoMessage() {}

func (x *LeaderboardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hometasker_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderboardRequest.ProtoReflect.Descriptor instead.
func (*LeaderboardRequest) Descriptor() ([]byte, []int) {
	return file_proto_hometasker_service_proto_rawDescGZIP(), []int{6}
}

type LeaderboardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*LeaderboardEntry    `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaderboardResponse) Reset() {
	*x = LeaderboardResponse{}
	mi := &file_proto_hometasker_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderboardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderboardResponse) ProtoMessage() {}

func (x *LeaderboardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hometasker_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderboardResponse.ProtoReflect.Descriptor instead.
func (*LeaderboardResponse) Descriptor() ([]byte, []int) {
	return file_proto_hometasker_service_proto_rawDescGZIP(), []int{7}
}

func (x *LeaderboardResponse) GetEntries() []*LeaderboardEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type LeaderboardEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          string                 `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Completed     int32                  `protobuf:"varint,2,opt,name=completed,proto3" json:"completed,omitempty"`
	OnTime        int32                  `protobuf:"varint,3,opt,name=on_time,json=onTime,proto3" json:"on_time,omitempty"`
	AvgEfficiency float32                `protobuf:"fixed32,4,opt,name=avg_efficiency,json=avgEfficiency,proto3" json:"avg_efficiency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaderboardEntry) Reset() {
	*x = LeaderboardEntry{}
	mi := &file_proto_hometasker_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderboardEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderboardEntry) ProtoMessage() {}

func (x *LeaderboardEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hometasker_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderboardEntry.ProtoReflect.Descriptor instead.
func (*LeaderboardEntry) Descriptor() ([]byte, []int) {
	return file_proto_hometasker_service_proto_rawDescGZIP(), []int{8}
}

func (x *LeaderboardEntry) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *LeaderboardEntry) GetCompleted() int32 {
	if x != nil {
		return x.Completed
	}
	return 0
}

func (x *LeaderboardEntry) GetOnTime() int32 {
	if x != nil {
		return x.OnTime
	}
	return 0
}

func (x *LeaderboardEntry) GetAvgEfficiency() float32 {
	if x != nil {
		return x.AvgEfficiency
	}
	return 0
}

var File_proto_hometasker_service_proto protoreflect.FileDescriptor

const file_proto_hometasker_service_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/hometasker_service.proto\x12\rhometasker.v1\"9\n" +
	"\x0fMarkTaskRequest\x12\x12\n" +
	"\x04task\x18\x01 \x01(\tR\x04task\x12\x12\n" +
	"\x04user\x18\x02 \x01(\tR\x04user\"\x12\n" +
	"\x10MarkTaskResponse\"C\n" +
	"\x11MarkReviewRequest\x12\x12\n" +
	"\x04task\x18\x01 \x01(\tR\x04task\x12\x1a\n" +
	"\breviewer\x18\x02 \x01(\tR\breviewer\"\x14\n" +
	"\x12MarkReviewResponse\"?\n" +
	"\x0eAddPileRequest\x12\x17\n" +
	"\apile_id\x18\x01 \x01(\tR\x06pileId\x12\x14\n" +
	"\x05delta\x18\x02 \x01(\x05R\x05delta\"\x11\n" +
	"\x0fAddPileResponse\"\x14\n" +
	"\x12LeaderboardRequest\"P\n" +
	"\x13LeaderboardResponse\x129\n" +
	"\aentries\x18\x01 \x03(\v2\x1f.hometasker.v1.LeaderboardEntryR\aentries\"\x84\x01\n" +
	"\x10LeaderboardEntry\x12\x12\n" +
	"\x04user\x18\x01 \x01(\tR\x04user\x12\x1c\n" +
	"\tcompleted\x18\x02 \x01(\x05R\tcompleted\x12\x17\n" +
	"\aon_time\x18\x03 \x01(\x05R\x06onTime\x12%\n" +
	"\x0eavg_efficiency\x18\x04 \x01(\x02R\ravgEfficiency2\xeb\x02\n" +
	"\x11HometaskerService\x12S\n" +
	"\x10MarkTaskComplete\x12\x1e.hometasker.v1.MarkTaskRequest\x1a\x1f.hometasker.v1.MarkTaskResponse\x12Y\n" +
	"\x12MarkReviewComplete\x12 .hometasker.v1.MarkReviewRequest\x1a!.hometasker.v1.MarkReviewResponse\x12M\n" +
	"\fAddPileValue\x12\x1d.hometasker.v1.AddPileRequest\x1a\x1e.hometasker.v1.AddPileResponse\x12W\n" +
	"\x0eGetLeaderboard\x12!.hometasker.v1.LeaderboardRequest\x1a\".hometasker.v1.LeaderboardResponseB\fZ\n" +
	"goproto/v1b\x06proto3"

var (
	file_proto_hometasker_service_proto_rawDescOnce sync.Once
	file_proto_hometasker_service_proto_rawDescData []byte
)

func file_proto_hometasker_service_proto_rawDescGZIP() []byte {
	file_proto_hometasker_service_proto_rawDescOnce.Do(func() {
		file_proto_hometasker_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_hometasker_service_proto_rawDesc), len(file_proto_hometasker_service_proto_rawDesc)))
	})
	return file_proto_hometasker_service_proto_rawDescData
}

var file_proto_hometasker_service_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_hometasker_service_proto_goTypes = []any{
	(*MarkTaskRequest)(nil),     // 0: hometasker.v1.MarkTaskRequest
	(*MarkTaskResponse)(nil),    // 1: hometasker.v1.MarkTaskResponse
	(*MarkReviewRequest)(nil),   // 2: hometasker.v1.MarkReviewRequest
	(*MarkReviewResponse)(nil),  // 3: hometasker.v1.MarkReviewResponse
	(*AddPileRequest)(nil),      // 4: hometasker.v1.AddPileRequest
	(*AddPileResponse)(nil),     // 5: hometasker.v1.AddPileResponse
	(*LeaderboardRequest)(nil),  // 6: hometasker.v1.LeaderboardRequest
	(*LeaderboardResponse)(nil), // 7: hometasker.v1.LeaderboardResponse
	(*LeaderboardEntry)(nil),    // 8: hometasker.v1.LeaderboardEntry
}
var file_proto_hometasker_service_proto_depIdxs = []int32{
	8, // 0: hometasker.v1.LeaderboardResponse.entries:type_name -> hometasker.v1.LeaderboardEntry
	0, // 1: hometasker.v1.HometaskerService.MarkTaskComplete:input_type -> hometasker.v1.MarkTaskRequest
	2, // 2: hometasker.v1.HometaskerService.MarkReviewComplete:input_type -> hometasker.v1.MarkReviewRequest
	4, // 3: hometasker.v1.HometaskerService.AddPileValue:input_type -> hometasker.v1.AddPileRequest
	6, // 4: hometasker.v1.HometaskerService.GetLeaderboard:input_type -> hometasker.v1.LeaderboardRequest
	1, // 5: hometasker.v1.HometaskerService.MarkTaskComplete:output_type -> hometasker.v1.MarkTaskResponse
	3, // 6: hometasker.v1.HometaskerService.MarkReviewComplete:output_type -> hometasker.v1.MarkReviewResponse
	5, // 7: hometasker.v1.HometaskerService.AddPileValue:output_type -> hometasker.v1.AddPileResponse
	7, // 8: hometasker.v1.HometaskerService.GetLeaderboard:output_type -> hometasker.v1.LeaderboardResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_hometasker_service_proto_init() }
func file_proto_hometasker_service_proto_init() {
	if File_proto_hometasker_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_hometasker_service_proto_rawDesc), len(file_proto_hometasker_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_hometasker_service_proto_goTypes,
		DependencyIndexes: file_proto_hometasker_service_proto_depIdxs,
		MessageInfos:      file_proto_hometasker_service_proto_msgTypes,
	}.Build()
	File_proto_hometasker_service_proto = out.File
	file_proto_hometasker_service_proto_goTypes = nil
	file_proto_hometasker_service_proto_depIdxs = nil
}
