syntax = "proto3";

package task;

option go_package = "github.com/DaDevFox/task-systems/tasker-core/backend/proto/v1";

import "tasker-core/backend/proto/v1/task.proto";
import "shared/proto/v1/query.proto";
import "shared/proto/v1/geography.proto";

message TagTextQuery {
  string tag = 1;
  string regex = 2;
}

message LocationDistanceSpecifier {
  geography.Position location = 1;
  double distance_meters = 2;
}

message RegionMembershipSpecifier { repeated geography.Position points = 1; }

message TagLocationQuery {
  string tag_id = 1;
  oneof specifier {
    LocationDistanceSpecifier location_distance = 2;
    RegionMembershipSpecifier region_membership = 3;
  }
}

message TagTimeQuery {
  string tag_id = 1;
  util.query.TimeQuery time_query = 2;
}

message TagQuery {
  oneof query {
    TagTextQuery text_query = 1;
    TagLocationQuery location_query = 2;
    TagTimeQuery time_query = 3;
  }
}

message TaskScheduleQuery {
  util.query.TimeQuery query = 1;
  TaskStatus status = 2;
}

message TaskQuerySpecifier {
  repeated TaskStatus can_have_stage =
      2; // will check for tasks (only) with one of
         // these statuses (this is a disjunction)
  repeated TaskStatus must_have_stage =
      3; // will check for tasks (only) with one of
         // these statuses (this is a disjunction)

  repeated TagQuery can_satisfy_tag =
      4; // will check for tasks (only) that satisfy at least one of these
         // (this is a disjunction); cannot be set with must_satisfy_tag
  repeated TagQuery must_satisfy_tag =
      5; // will check for tasks (only) that satisfy all of these
         // (this is a conjunction); cannot be set with can_satisfy_tag

  repeated TaskScheduleQuery can_satisfy_stage =
      6; // will check for tasks (only) that satisfy at least one of these
         // (this is a disjunction); cannot be set with must_satisfy_stage
  repeated TaskScheduleQuery must_satisfy_stage =
      7; // will check for tasks (only) that satisfy all of these
         // (this is a conjunction); cannot be set with can_satisfy_stage

  repeated util.query.TimeQuery can_have_been_created_during =
      8; // will check for tasks (only) that were created during at least one of
         // these time ranges (this is a disjunction); cannot be set with
         // must_have_been_created_during
  repeated util.query.TimeQuery must_have_been_created_during =
      9; // will check for tasks (only) that were created during at least one of
         // these time ranges (this is a conjunction); cannot be set with
         // can_have_been_created_during

  repeated util.query.TimeQuery can_have_been_modified_during =
      10; // will check for tasks (only) that were modified during at least one
          // of these time ranges (this is a disjunction); cannot be set with
          // must_have_been_modified_during
  repeated util.query.TimeQuery must_have_been_modified_during =
      11; // will check for tasks (only) that were modified during at least one
          // of these time ranges (this is a conjunction); cannot be set with
          // can_have_been_modified_during
}

enum JoinType {
  CONJUNCTION = 0; // CONJUNCTION intersects the results of the queries
  DISJUNCTION = 1; // DISJUNCTION unions the results of the queries
  NOT = 2;         // in the case of NOT, only element a needs to
                   // be present; it will be inverted
}

message Join {
  TaskQuery a = 1;
  TaskQuery b = 2;
  JoinType type = 3;
}

message TaskQuery {
  oneof query {
    Join join = 1;
    TaskQuerySpecifier terminal = 2;
  }
}
