syntax = "proto3";
// TODO:
// https://golang.elitedev.in/golang/production-ready-grpc-microservices-in-go-authentication-service-discovery-and-observability-guid-865353d1/
// https://dev.to/techschoolguru/use-grpc-interceptor-for-authorization-with-jwt-1c5h

package user;

option go_package = "github.com/DaDevFox/task-systems/user-core/backend/pkg/proto/v1";

import "user-core/backend/proto/v1/group.proto";

message MemberQuery {
  string id = 1;
  repeated Privilege privilege =
      2; // will check for membership (only) with one of these privileges
}

message Specifier {
  repeated MemberQuery part_of = 1;
  repeated MemberQuery not_part_of = 2;
}

enum JoinType {
  CONJUNCTION = 0; // CONJUNCTION intersects the results of the queries
  DISJUNCTION = 1; // DISJUNCTION unions the results of the queries
  NOT = 2;         // in the case of NOT, only element a needs to
                   // be present; it will be inverted
}

message Join {
  UserQuery a = 1;
  UserQuery b = 2;
  JoinType type = 3;
}

message UserQuery {
  oneof query {
    Join join = 1;
    Specifier terminal = 2;
  }
}

/* example:
 * plaintext: (part_of #resource-Y-eligible && !(part_of #pii-readers && part_of
 * #suspected-compromise))
 * {
 *  join {
 *   type = CONJUNCTION
 *    a {
 *      terminal {
 *        part_of {
 *          id = "#resource-Y-eligible"
 *        }
 *      }
 *    }
 *    b {
 *      join {
 *        type = NOT
 *        a{
 *         join {
 *          type = CONJUNCTION
 *          a {
 *           terminal {
 *             part_of {
 *               id = "#pii-readers"
 *             }
 *           }
 *          }
 *          b {
 *           terminal {
 *             part_of {
 *               id = "#suspected-compromise"
 *             }
 *           }
 *         }
 *        }
 *      }
 *      }
 *    }
 *  }
 * }
 */
