syntax = "proto3";
// TODO:
// https://golang.elitedev.in/golang/production-ready-grpc-microservices-in-go-authentication-service-discovery-and-observability-guid-865353d1/
// https://dev.to/techschoolguru/use-grpc-interceptor-for-authorization-with-jwt-1c5h

package user;

option go_package = "github.com/DaDevFox/task-systems/user-core/backend/pkg/proto/v1";

import "user-core/backend/proto/v1/group.proto";

// USER QUERIES

message TextQuery {
  string regex_match_exactly = 1;
  repeated string contains_regex_matches = 2;
}

message InexactTextQuery {
  repeated string similar_to = 1;
}

message ApproximateUserSpecifier {
  oneof name {
    TextQuery exact_name = 1;
    InexactTextQuery inexact_name = 2;
  }
  oneof id {
    TextQuery exact_id = 3;
    InexactTextQuery inexact_id = 4;
  }
}

message ApproximateUserJoin {
  ApproximateUserQuery a = 1;
  ApproximateUserQuery b = 2;
  JoinType type = 3;
}

message ApproximateUserQuery {
  oneof query {
    ApproximateUserSpecifier terminal = 1;
    ApproximateUserJoin join = 2;
  }
}

message UserJoin {
  UserQuery a = 1;
  UserQuery b = 2;
  JoinType type = 3;
}

message UserSpecifier {
  TextQuery name = 1;
  TextQuery id = 2;
}

message UserQuery {
  oneof query {
    UserJoin join = 1;
    UserSpecifier terminal = 2;
  }
}


// GROUP QUERIES

message InexactMemberQuery {
  string text_query = 1;
  repeated Privilege privilege = 2;
}

message ApproximateMemberQuery {
  oneof query {
    InexactMemberQuery inexact = 1;
    MemberQuery exact = 2;
  }
}

message ApproximateUserGroupQuery {
  oneof query {
    ApproximateJoin join = 1;
    ApproximateSpecifier terminal = 2;
  }
}

message ApproximateJoin{
  ApproximateUserGroupQuery a = 1;
  ApproximateUserGroupQuery b = 2;
  JoinType type = 3;
}

message ApproximateSpecifier {
  repeated ApproximateMemberQuery part_of = 1;
  repeated ApproximateMemberQuery not_part_of = 2;
  string id_text_query = 3;
}

// PROPER user queries below (look at those for filters, above are for searches with 'approximate' results)

message MemberQuery {
  string exact_id = 1;
  repeated Privilege privilege =
      2; // will check for membership (only) with one of these privileges
  string regex_match = 3;
}

message Specifier {
  repeated MemberQuery part_of = 1;
  repeated MemberQuery not_part_of = 2;
  string id_regex_match = 3;
}

enum JoinType {
  CONJUNCTION = 0; // CONJUNCTION intersects the results of the queries
  DISJUNCTION = 1; // DISJUNCTION unions the results of the queries
  NOT = 2;         // in the case of NOT, only element a needs to
                   // be present; it will be inverted
}

message Join {
  UserGroupQuery a = 1;
  UserGroupQuery b = 2;
  JoinType type = 3;
}

message UserGroupQuery {
  oneof query {
    Join join = 1;
    Specifier terminal = 2;
  }
}

/* example:
 * plaintext: (part_of #resource-Y-eligible && !(part_of #pii-readers && part_of
 * #suspected-compromise))
 * {
 *  join {
 *   type = CONJUNCTION
 *    a {
 *      terminal {
 *        part_of {
 *          id = "#resource-Y-eligible"
 *        }
 *      }
 *    }
 *    b {
 *      join {
 *        type = NOT
 *        a{
 *         join {
 *          type = CONJUNCTION
 *          a {
 *           terminal {
 *             part_of {
 *               id = "#pii-readers"
 *             }
 *           }
 *          }
 *          b {
 *           terminal {
 *             part_of {
 *               id = "#suspected-compromise"
 *             }
 *           }
 *         }
 *        }
 *      }
 *      }
 *    }
 *  }
 * }
 */
